export type PlanModality = "individual" | "semi_private_2" | "group_3" | "group_4" | "flexible_1x";

export interface CatalogPlan {
  id: string;
  name: string;
  description: string;
  modality: PlanModality;
  durationMonths: number;
  totalClasses: number;
  sessionsPerWeek: 1 | 2;
  students: 1 | 2 | 3 | 4;
  price: number;
  currency: "CLP";
  popular?: boolean;
  features: string[];
}

export const PLAN_MODALITY_META: Record<
  PlanModality,
  { title: string; subtitle: string; badge: string }
> = {
  individual: {
    title: "Individual",
    subtitle: "Experiencia 100% personalizada",
    badge: "1 persona",
  },
  semi_private_2: {
    title: "Semi-Privado",
    subtitle: "Avanza acompa\u00f1ado. M\u00e1s interacci\u00f3n, menor inversi\u00f3n.",
    badge: "2 personas",
  },
  group_3: {
    title: "Grupal",
    subtitle: "Din\u00e1mico, colaborativo y efectivo",
    badge: "3 personas",
  },
  group_4: {
    title: "Grupal",
    subtitle: "La opci\u00f3n m\u00e1s conveniente por persona",
    badge: "4 personas",
  },
  flexible_1x: {
    title: "Individual Flexible",
    subtitle: "1 sesi\u00f3n semanal para mayor flexibilidad",
    badge: "1 vez por semana",
  },
};

const SHARED_FEATURES = [
  "Metodolog\u00eda comunicativa",
  "Material digital personalizado",
  "Seguimiento y feedback constante",
  "Enfoque en ingl\u00e9s general y profesional",
];

export const PLAN_CATALOG: CatalogPlan[] = [
  {
    id: "test-1",
    name: "Test 1",
    description: "Plan temporal para prueba de pago en Mercado Pago.",
    modality: "individual",
    durationMonths: 1,
    totalClasses: 1,
    sessionsPerWeek: 1,
    students: 1,
    price: 500,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "individual-1m-8c",
    name: "Individual 1 mes",
    description: "8 clases online de 60 minutos, 2 veces por semana.",
    modality: "individual",
    durationMonths: 1,
    totalClasses: 8,
    sessionsPerWeek: 2,
    students: 1,
    price: 148000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "individual-2m-16c",
    name: "Individual 2 meses",
    description: "16 clases online de 60 minutos, 2 veces por semana.",
    modality: "individual",
    durationMonths: 2,
    totalClasses: 16,
    sessionsPerWeek: 2,
    students: 1,
    price: 288000,
    currency: "CLP",
    popular: true,
    features: SHARED_FEATURES,
  },
  {
    id: "individual-3m-24c",
    name: "Individual 3 meses",
    description: "24 clases online de 60 minutos, 2 veces por semana.",
    modality: "individual",
    durationMonths: 3,
    totalClasses: 24,
    sessionsPerWeek: 2,
    students: 1,
    price: 420000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "individual-4m-32c",
    name: "Individual 4 meses",
    description: "32 clases online de 60 minutos, 2 veces por semana.",
    modality: "individual",
    durationMonths: 4,
    totalClasses: 32,
    sessionsPerWeek: 2,
    students: 1,
    price: 544000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "semi2-1m",
    name: "Semi-Privado 1 mes",
    description: "Plan para 2 personas, 2 sesiones semanales de 60 minutos.",
    modality: "semi_private_2",
    durationMonths: 1,
    totalClasses: 8,
    sessionsPerWeek: 2,
    students: 2,
    price: 136000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "semi2-2m",
    name: "Semi-Privado 2 meses",
    description: "Plan para 2 personas con descuento por pago anticipado.",
    modality: "semi_private_2",
    durationMonths: 2,
    totalClasses: 16,
    sessionsPerWeek: 2,
    students: 2,
    price: 256000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "semi2-3m",
    name: "Semi-Privado 3 meses",
    description: "Plan para 2 personas con continuidad de aprendizaje.",
    modality: "semi_private_2",
    durationMonths: 3,
    totalClasses: 24,
    sessionsPerWeek: 2,
    students: 2,
    price: 372000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "semi2-4m",
    name: "Semi-Privado 4 meses",
    description: "Plan para 2 personas con avance sostenido.",
    modality: "semi_private_2",
    durationMonths: 4,
    totalClasses: 32,
    sessionsPerWeek: 2,
    students: 2,
    price: 480000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "group3-1m",
    name: "Grupal 3 personas 1 mes",
    description: "Modalidad grupal din\u00e1mica de 3 personas.",
    modality: "group_3",
    durationMonths: 1,
    totalClasses: 8,
    sessionsPerWeek: 2,
    students: 3,
    price: 120000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "group3-2m",
    name: "Grupal 3 personas 2 meses",
    description: "Plan colaborativo para avanzar en equipo.",
    modality: "group_3",
    durationMonths: 2,
    totalClasses: 16,
    sessionsPerWeek: 2,
    students: 3,
    price: 224000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "group3-3m",
    name: "Grupal 3 personas 3 meses",
    description: "Mayor continuidad para consolidar resultados.",
    modality: "group_3",
    durationMonths: 3,
    totalClasses: 24,
    sessionsPerWeek: 2,
    students: 3,
    price: 324000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "group3-4m",
    name: "Grupal 3 personas 4 meses",
    description: "Ruta completa para trabajo sostenido en grupo.",
    modality: "group_3",
    durationMonths: 4,
    totalClasses: 32,
    sessionsPerWeek: 2,
    students: 3,
    price: 416000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "group4-1m",
    name: "Grupal 4 personas 1 mes",
    description: "La opci\u00f3n m\u00e1s conveniente por persona.",
    modality: "group_4",
    durationMonths: 1,
    totalClasses: 8,
    sessionsPerWeek: 2,
    students: 4,
    price: 104000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "group4-2m",
    name: "Grupal 4 personas 2 meses",
    description: "M\u00e1s ahorro manteniendo enfoque comunicativo.",
    modality: "group_4",
    durationMonths: 2,
    totalClasses: 16,
    sessionsPerWeek: 2,
    students: 4,
    price: 192000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "group4-3m",
    name: "Grupal 4 personas 3 meses",
    description: "Continuidad ideal para progreso medible.",
    modality: "group_4",
    durationMonths: 3,
    totalClasses: 24,
    sessionsPerWeek: 2,
    students: 4,
    price: 276000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "group4-4m",
    name: "Grupal 4 personas 4 meses",
    description: "Programa completo con inversi\u00f3n optimizada.",
    modality: "group_4",
    durationMonths: 4,
    totalClasses: 32,
    sessionsPerWeek: 2,
    students: 4,
    price: 352000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "flex-1m-4c",
    name: "Flexible 1 mes",
    description: "4 clases online de 60 minutos, 1 vez por semana.",
    modality: "flexible_1x",
    durationMonths: 1,
    totalClasses: 4,
    sessionsPerWeek: 1,
    students: 1,
    price: 76000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "flex-2m-8c",
    name: "Flexible 2 meses",
    description: "8 clases online de 60 minutos, 1 vez por semana.",
    modality: "flexible_1x",
    durationMonths: 2,
    totalClasses: 8,
    sessionsPerWeek: 1,
    students: 1,
    price: 148000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "flex-3m-12c",
    name: "Flexible 3 meses",
    description: "12 clases online de 60 minutos, 1 vez por semana.",
    modality: "flexible_1x",
    durationMonths: 3,
    totalClasses: 12,
    sessionsPerWeek: 1,
    students: 1,
    price: 216000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
  {
    id: "flex-4m-16c",
    name: "Flexible 4 meses",
    description: "16 clases online de 60 minutos, 1 vez por semana.",
    modality: "flexible_1x",
    durationMonths: 4,
    totalClasses: 16,
    sessionsPerWeek: 1,
    students: 1,
    price: 272000,
    currency: "CLP",
    features: SHARED_FEATURES,
  },
];

export function findCatalogPlanById(planId: string) {
  return PLAN_CATALOG.find((plan) => plan.id === planId);
}

export function getPlansByModality(modality: PlanModality) {
  return PLAN_CATALOG.filter((plan) => plan.modality === modality).sort(
    (a, b) => a.durationMonths - b.durationMonths
  );
}

export function getCatalogPlanIds() {
  return PLAN_CATALOG.map((plan) => plan.id);
}
